name: Code analysis checks
on: [push]
jobs:
  codeanalysis:
    runs-on: ubuntu-latest

    steps:
      - name: Main checkout
        uses: actions/checkout@v3

      - name: Linting
        run: make lint
